/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TvIndexRouteImport } from './routes/tv/index'
import { Route as TrendingIndexRouteImport } from './routes/trending/index'
import { Route as TopRatedIndexRouteImport } from './routes/top-rated/index'
import { Route as SearchIndexRouteImport } from './routes/search/index'
import { Route as OriginalsIndexRouteImport } from './routes/originals/index'
import { Route as MoviesIndexRouteImport } from './routes/movies/index'
import { Route as AnimeIndexRouteImport } from './routes/anime/index'
import { Route as WatchIdRouteImport } from './routes/watch/$id'
import { Route as ProductsProductIdRouteImport } from './routes/products/$productId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TvIndexRoute = TvIndexRouteImport.update({
  id: '/tv/',
  path: '/tv/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrendingIndexRoute = TrendingIndexRouteImport.update({
  id: '/trending/',
  path: '/trending/',
  getParentRoute: () => rootRouteImport,
} as any)
const TopRatedIndexRoute = TopRatedIndexRouteImport.update({
  id: '/top-rated/',
  path: '/top-rated/',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchIndexRoute = SearchIndexRouteImport.update({
  id: '/search/',
  path: '/search/',
  getParentRoute: () => rootRouteImport,
} as any)
const OriginalsIndexRoute = OriginalsIndexRouteImport.update({
  id: '/originals/',
  path: '/originals/',
  getParentRoute: () => rootRouteImport,
} as any)
const MoviesIndexRoute = MoviesIndexRouteImport.update({
  id: '/movies/',
  path: '/movies/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnimeIndexRoute = AnimeIndexRouteImport.update({
  id: '/anime/',
  path: '/anime/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/watch/$id': typeof WatchIdRoute
  '/anime/': typeof AnimeIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/originals/': typeof OriginalsIndexRoute
  '/search/': typeof SearchIndexRoute
  '/top-rated/': typeof TopRatedIndexRoute
  '/trending/': typeof TrendingIndexRoute
  '/tv/': typeof TvIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/watch/$id': typeof WatchIdRoute
  '/anime': typeof AnimeIndexRoute
  '/movies': typeof MoviesIndexRoute
  '/originals': typeof OriginalsIndexRoute
  '/search': typeof SearchIndexRoute
  '/top-rated': typeof TopRatedIndexRoute
  '/trending': typeof TrendingIndexRoute
  '/tv': typeof TvIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/watch/$id': typeof WatchIdRoute
  '/anime/': typeof AnimeIndexRoute
  '/movies/': typeof MoviesIndexRoute
  '/originals/': typeof OriginalsIndexRoute
  '/search/': typeof SearchIndexRoute
  '/top-rated/': typeof TopRatedIndexRoute
  '/trending/': typeof TrendingIndexRoute
  '/tv/': typeof TvIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/products/$productId'
    | '/watch/$id'
    | '/anime/'
    | '/movies/'
    | '/originals/'
    | '/search/'
    | '/top-rated/'
    | '/trending/'
    | '/tv/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/products/$productId'
    | '/watch/$id'
    | '/anime'
    | '/movies'
    | '/originals'
    | '/search'
    | '/top-rated'
    | '/trending'
    | '/tv'
  id:
    | '__root__'
    | '/'
    | '/products/$productId'
    | '/watch/$id'
    | '/anime/'
    | '/movies/'
    | '/originals/'
    | '/search/'
    | '/top-rated/'
    | '/trending/'
    | '/tv/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  WatchIdRoute: typeof WatchIdRoute
  AnimeIndexRoute: typeof AnimeIndexRoute
  MoviesIndexRoute: typeof MoviesIndexRoute
  OriginalsIndexRoute: typeof OriginalsIndexRoute
  SearchIndexRoute: typeof SearchIndexRoute
  TopRatedIndexRoute: typeof TopRatedIndexRoute
  TrendingIndexRoute: typeof TrendingIndexRoute
  TvIndexRoute: typeof TvIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tv/': {
      id: '/tv/'
      path: '/tv'
      fullPath: '/tv/'
      preLoaderRoute: typeof TvIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trending/': {
      id: '/trending/'
      path: '/trending'
      fullPath: '/trending/'
      preLoaderRoute: typeof TrendingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/top-rated/': {
      id: '/top-rated/'
      path: '/top-rated'
      fullPath: '/top-rated/'
      preLoaderRoute: typeof TopRatedIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search/': {
      id: '/search/'
      path: '/search'
      fullPath: '/search/'
      preLoaderRoute: typeof SearchIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/originals/': {
      id: '/originals/'
      path: '/originals'
      fullPath: '/originals/'
      preLoaderRoute: typeof OriginalsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/movies/': {
      id: '/movies/'
      path: '/movies'
      fullPath: '/movies/'
      preLoaderRoute: typeof MoviesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/anime/': {
      id: '/anime/'
      path: '/anime'
      fullPath: '/anime/'
      preLoaderRoute: typeof AnimeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  WatchIdRoute: WatchIdRoute,
  AnimeIndexRoute: AnimeIndexRoute,
  MoviesIndexRoute: MoviesIndexRoute,
  OriginalsIndexRoute: OriginalsIndexRoute,
  SearchIndexRoute: SearchIndexRoute,
  TopRatedIndexRoute: TopRatedIndexRoute,
  TrendingIndexRoute: TrendingIndexRoute,
  TvIndexRoute: TvIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
